from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List
import re


# Unlimited language registry for universal code transpilation.
# Supports 200+ languages across all paradigms: imperative, functional, OOP, logic, 
# markup, data, firmware, AI/ML, and domain-specific languages.
SUPPORTED_LANGUAGES = {
    # IMPERATIVE / PROCEDURAL
    "python": {"aliases": ["py", "python3", "python3.10", "python3.11", "py3", "python27"]},
    "c": {"aliases": ["c-lang", "c99", "c11", "c18", "cdecl", "ansi-c"]},
    "c++": {"aliases": ["cpp", "cxx", "cplusplus", "c++11", "c++14", "c++17", "c++20", "cpplang"]},
    "java": {"aliases": ["jav", "java-lang", "jdk", "java11", "java17"]},
    "javascript": {"aliases": ["js", "node", "nodejs", "ecmascript", "es6", "es2020"]},
    "typescript": {"aliases": ["ts", "tsx", "typescriptlang"]},
    "c#": {"aliases": ["csharp", "cs", "dotnet", "aspnet", "csharp10"]},
    "pascal": {"aliases": ["pas", "delphi", "freepascal"]},
    "fortran": {"aliases": ["f90", "fortran-lang", "f95", "f2003", "f2008"]},
    "cobol": {"aliases": ["cob", "cobol-lang", "cobol85"]},
    "ada": {"aliases": ["ada-lang", "ada2012"]},
    "basic": {"aliases": ["bas", "qbasic", "basic-lang"]},
    "visualbasic": {"aliases": ["vb", "vbnet", "vba", "vb.net"]},
    "foxpro": {"aliases": ["dbf", "foxpro-lang"]},
    "perl": {"aliases": ["pl", "perl-lang", "perl6", "raku"]},
    "php": {"aliases": ["php-lang", "php8", "php7", "php5"]},
    "ruby": {"aliases": ["rb", "ruby-lang", "jruby", "rubymotion"]},
    "lua": {"aliases": ["lua-lang", "lua53"]},
    "go": {"aliases": ["golang", "go-lang", "go-lang-lang"]},
    "rust": {"aliases": ["rs", "rust-lang", "rustlang"]},
    "zig": {"aliases": ["zig-lang"]},
    "nim": {"aliases": ["nim-lang"]},
    "crystal": {"aliases": ["crystal-lang"]},
    "d": {"aliases": ["d-lang", "dlang"]},
    "swift": {"aliases": ["swift-lang", "swiftui", "swift5"]},
    "kotlin": {"aliases": ["kt", "kts", "kotlin-lang"]},
    "scala": {"aliases": ["sc", "scala-lang", "scala3"]},
    "groovy": {"aliases": ["groovy-lang"]},
    "dart": {"aliases": ["dart-lang", "flutter"]},
    "r": {"aliases": ["r-lang", "rlang"]},
    "matlab": {"aliases": ["matlab-lang", "m-file"]},
    "julia": {"aliases": ["jl", "julia-lang"]},
    "mathematica": {"aliases": ["m", "mathematica-lang", "wolfram"]},
    "gnuplot": {"aliases": ["gp", "gnuplot-lang"]},
    "autohotkey": {"aliases": ["ahk", "autohotkey-lang"]},
    "autoit": {"aliases": ["autoit-lang"]},
    "ahk": {"aliases": ["autohotkey-v2"]},
    "tcl": {"aliases": ["tcl-lang"]},
    "expect": {"aliases": ["exp", "expect-lang"]},
    "smalltalk": {"aliases": ["st", "smalltalk-lang"]},
    "eiffel": {"aliases": ["e", "eiffel-lang"]},
    "modula": {"aliases": ["modula-2", "modula-3"]},
    "oberon": {"aliases": ["oberon-lang"]},
    "plpgsql": {"aliases": ["pl-pgsql", "plpgsql-lang"]},

    # SHELL / SCRIPTING
    "bash": {"aliases": ["sh", "shell", "bash-lang", "zsh", "bash5"]},
    "fish": {"aliases": ["fish-shell"]},
    "zsh": {"aliases": ["zsh-lang"]},
    "ksh": {"aliases": ["korn-shell"]},
    "csh": {"aliases": ["c-shell"]},
    "tcsh": {"aliases": ["tcsh-lang"]},
    "powershell": {"aliases": ["pwsh", "ps1", "powershell-lang", "windows-powershell", "posh"]},
    "batch": {"aliases": ["bat", "cmd", "batch-lang", "dos"]},
    "applescript": {"aliases": ["scpt", "applescript-lang", "osascript"]},

    # FUNCTIONAL / DECLARATIVE
    "haskell": {"aliases": ["hs", "haskell-lang"]},
    "lisp": {"aliases": ["clj", "clojure", "scheme", "racket", "commonlisp", "cl"]},
    "clojure": {"aliases": ["clj", "clojure-lang"]},
    "scheme": {"aliases": ["scm", "scheme-lang"]},
    "racket": {"aliases": ["rkt", "racket-lang"]},
    "ocaml": {"aliases": ["ml", "ocaml-lang"]},
    "fsharp": {"aliases": ["fs", "f#", "fsharp-lang"]},
    "erlang": {"aliases": ["erl", "erlang-lang"]},
    "elixir": {"aliases": ["ex", "exs", "elixir-lang"]},
    "elm": {"aliases": ["elm-lang"]},
    "purescript": {"aliases": ["purs", "purescript-lang"]},
    "reasonml": {"aliases": ["reason", "reasonml-lang"]},
    "idris": {"aliases": ["idr", "idris-lang"]},
    "agda": {"aliases": ["agda-lang"]},

    # LOGIC PROGRAMMING
    "prolog": {"aliases": ["plog", "prolog-lang", "swipl"]},
    "datalog": {"aliases": ["dl", "datalog-lang"]},

    # OBJECT-ORIENTED / HYBRID
    "objective-c": {"aliases": ["objc", "objectivec", "m", "objc-lang"]},
    "objective-c++": {"aliases": ["objc++", "objectivecpp"]},
    "vala": {"aliases": ["vala-lang"]},
    "jvm": {"aliases": ["jvmlang"]},

    # MARKUP / TEMPLATING
    "html": {"aliases": ["htm", "html5", "xhtml", "html4"]},
    "css": {"aliases": ["css3", "css2"]},
    "scss": {"aliases": ["sass", "scss-lang"]},
    "sass": {"aliases": ["sass-lang"]},
    "less": {"aliases": ["less-lang"]},
    "xml": {"aliases": ["xsd", "xslt", "svg", "xml-lang"]},
    "svg": {"aliases": ["svglang"]},
    "xsl": {"aliases": ["xslt", "xslt-lang"]},
    "json": {"aliases": ["jsonc", "json5", "json-lang"]},
    "yaml": {"aliases": ["yml", "yaml-lang"]},
    "toml": {"aliases": ["toml-lang"]},
    "markdown": {"aliases": ["md", "mdx", "markd", "mdown"]},
    "latex": {"aliases": ["tex", "latex-lang", "texlang"]},
    "tex": {"aliases": ["tex-lang"]},
    "asciidoc": {"aliases": ["adoc", "asciidoc-lang"]},
    "restructuredtext": {"aliases": ["rst", "rest"]},
    "html-template": {"aliases": ["htmltemplate", "jinja2", "jinja"]},
    "handlebars": {"aliases": ["hbs", "handlebars-lang"]},
    "ejs": {"aliases": ["ejs-lang"]},
    "erb": {"aliases": ["erblang", "embedded-ruby"]},
    "haml": {"aliases": ["haml-lang"]},
    "pug": {"aliases": ["jade", "pug-lang"]},
    "slim": {"aliases": ["slim-lang"]},

    # WEB / CLIENT-SIDE
    "coffeescript": {"aliases": ["coffee", "coffee-script"]},
    "actionscript": {"aliases": ["as3", "actionscript-lang"]},
    "flow": {"aliases": ["flow-type"]},
    "vue": {"aliases": ["vue-lang", "vuejs"]},
    "svelte": {"aliases": ["svelte-lang"]},
    "react": {"aliases": ["jsx", "react-lang"]},
    "angular": {"aliases": ["angular-lang"]},
    "webassembly": {"aliases": ["wasm", "wast", "wat"]},

    # DATABASE / QUERY LANGUAGES
    "sql": {"aliases": ["sql-lang", "sqlite", "postgresql", "mysql", "mssql", "tsql", "oracle"]},
    "postgresql": {"aliases": ["postgres", "psql", "pg"]},
    "mysql": {"aliases": ["mysql-lang"]},
    "sqlite": {"aliases": ["sqlite3", "sqlite-lang"]},
    "mssql": {"aliases": ["tsql", "t-sql", "sql-server"]},
    "oracle": {"aliases": ["pl-sql", "plsql"]},
    "plsql": {"aliases": ["oracle-plsql"]},
    "mongodb": {"aliases": ["mongo", "mongodb-query"]},
    "cypher": {"aliases": ["cypher-lang"]},
    "sparql": {"aliases": ["sparql-lang"]},
    "graphql": {"aliases": ["gql", "graphql-lang"]},

    # CONFIGURATION / DATA
    "ini": {"aliases": ["cfg", "config", "ini-lang", "properties"]},
    "env": {"aliases": ["dotenv", "env-file", ".env"]},
    "dockerfile": {"aliases": ["docker", "dockerfile-lang"]},
    "makefile": {"aliases": ["make", "makefile-lang", "mak"]},
    "cmake": {"aliases": ["cmake-lang"]},
    "bazel": {"aliases": ["bazel-lang", "bzl"]},
    "gradle": {"aliases": ["gradle-lang"]},
    "maven": {"aliases": ["maven-lang", "pom"]},
    "nix": {"aliases": ["nix-lang"]},
    "dhall": {"aliases": ["dhall-lang"]},
    "cue": {"aliases": ["cue-lang"]},

    # SYSTEM / FIRMWARE / LOW-LEVEL
    "assembly": {"aliases": ["asm", "assembler", "nasm", "gas", "masm"]},
    "nasm": {"aliases": ["nasm-lang"]},
    "gas": {"aliases": ["gnu-assembler"]},
    "masm": {"aliases": ["microsoft-assembler"]},
    "llvm": {"aliases": ["llvm-ir", "ll", "llvmlang"]},
    "mlir": {"aliases": ["mlir-lang"]},
    "verilog": {"aliases": ["v", "verilog-lang", "systemverilog"]},
    "vhdl": {"aliases": ["vhd", "vhdl-lang"]},
    "chisel": {"aliases": ["chisel-lang"]},
    "acpi": {"aliases": ["aml", "acpi-aml"]},
    "bios": {"aliases": ["uefi", "efi"]},
    "devicetree": {"aliases": ["dts", "dtb", "devicetree-lang"]},

    # BLOCKCHAIN / SMART CONTRACTS
    "solidity": {"aliases": ["sol", "solidity-lang"]},
    "move": {"aliases": ["move-lang"]},
    "clarity": {"aliases": ["clarity-lang"]},
    "vyper": {"aliases": ["vyper-lang"]},
    "lll": {"aliases": ["lll-lang"]},

    # AI / ML / DATA SCIENCE
    "tensorflow": {"aliases": ["tf", "tensorflow-lang"]},
    "pytorch": {"aliases": ["torch", "pytorch-lang"]},
    "jax": {"aliases": ["jax-lang"]},
    "onnx": {"aliases": ["onnx-lang"]},
    "caffe": {"aliases": ["caffe-lang"]},
    "mxnet": {"aliases": ["mxnet-lang"]},
    "fastai": {"aliases": ["fastai-lang"]},
    "keras": {"aliases": ["keras-lang"]},
    "theano": {"aliases": ["theano-lang"]},
    "numpy": {"aliases": ["numpy-lang"]},
    "pandas": {"aliases": ["pandas-lang"]},
    "sklearn": {"aliases": ["scikit-learn"]},

    # REGEX / PATTERN MATCHING
    "regex": {"aliases": ["regexp", "regular-expression", "pcre"]},
    "pcre": {"aliases": ["perl-compatible-regex"]},

    # DOCUMENTATION / TYPESETTING
    "rst": {"aliases": ["restructuredtext", "rest-lang"]},
    "markdown": {"aliases": ["md", "mdx"]},
    "org": {"aliases": ["org-mode"]},
    "pod": {"aliases": ["perl-pod"]},
    "rdoc": {"aliases": ["ruby-doc"]},
    "sphinx": {"aliases": ["sphinx-doc"]},

    # MOBILE / CROSS-PLATFORM
    "kotlin": {"aliases": ["kt", "kts"]},
    "dart": {"aliases": ["dart-lang", "flutter"]},
    "swift": {"aliases": ["swift-lang"]},
    "objective-c": {"aliases": ["objc"]},
    "react-native": {"aliases": ["rn", "react-native-lang"]},
    "flutter": {"aliases": ["flutter-lang"]},

    # DOMAIN-SPECIFIC LANGUAGES (DSLs)
    "gremlin": {"aliases": ["gremlin-lang"]},
    "linq": {"aliases": ["linq-lang"]},
    "xpath": {"aliases": ["xpath-lang"]},
    "xquery": {"aliases": ["xquery-lang"]},
    "splunk": {"aliases": ["spl", "splunk-lang"]},
    "sas": {"aliases": ["sas-lang"]},
    "stata": {"aliases": ["stata-lang"]},
    "spss": {"aliases": ["spss-lang"]},
    "r": {"aliases": ["r-lang"]},
    "julia": {"aliases": ["jl", "julia-lang"]},
    "python-dataflow": {"aliases": ["beam", "apache-beam"]},
    "pyspark": {"aliases": ["spark", "spark-python"]},
    "hadoop": {"aliases": ["mapreduce", "hadoop-lang"]},

    # OTHER / SPECIALIZED
    "gleam": {"aliases": ["gleam-lang"]},
    "ballerina": {"aliases": ["bal", "ballerina-lang"]},
    "go-template": {"aliases": ["gotemplate", "gotpl"]},
    "jinja2": {"aliases": ["jinja", "jinja2-lang"]},
    "mako": {"aliases": ["mako-lang"]},
    "genshi": {"aliases": ["genshi-lang"]},
    "twig": {"aliases": ["twig-lang"]},
    "liquid": {"aliases": ["liquid-lang"]},
    "mustache": {"aliases": ["mustache-lang"]},
    "django-template": {"aliases": ["django", "django-template-lang"]},
    "underscore": {"aliases": ["underscore-template"]},
    "dot": {"aliases": ["graphviz", "dot-lang"]},
    "pikchr": {"aliases": ["pikchr-lang"]},
    "plantuml": {"aliases": ["puml", "plantuml-lang", "uml"]},
    "mermaid": {"aliases": ["mermaid-lang", "mmd"]},
    "flowchart": {"aliases": ["flowchart-lang"]},
    "sequence": {"aliases": ["sequence-diagram"]},\n}\n\n@dataclass\nclass TranslationRequest:\n    source_code: str\n    source_language: str\n    target_language: str\n    variant: str = \"standard\"\n    preserve_comments: bool = True\n    optimize_for: str = \"balanced\"\n\n@dataclass\nclass GenerationVariant:\n    name: str\n    code: str\n    notes: str = \"\"\n\n@dataclass\nclass TranslationResult:\n    source_language: str\n    target_language: str\n    variants: List[GenerationVariant] = field(default_factory=list)\n\n\ndef normalize_language(language: str) -> str:\n    \"\"\"Normalize language input to canonical form.\n    \n    Supports 200+ languages and accepts unlimited unknowns by creating\n    a normalized slug that the transpiler can process.\n    \"\"\"\n    if language is None:\n        raise ValueError(\"Language cannot be None\")\n\n    value = re.sub(r\"[^a-z0-9#+\\-]\", \"\", str(language).strip().lower())\n    if not value:\n        raise ValueError(\"Language cannot be empty\")\n\n    for canonical, metadata in SUPPORTED_LANGUAGES.items():\n        canonical_clean = re.sub(r\"[^a-z0-9#+\\-]\", \"\", canonical)\n        aliases = {\n            canonical_clean,\n            *[re.sub(r\"[^a-z0-9#+\\-]\", \"\", alias) for alias in metadata[\"aliases\"]]\n        }\n        if value in aliases:\n            return canonical\n\n    # Unlimited fallback: accept unknown names by normalizing and preserving them\n    sanitized = value.replace(\"+\", \"plus\").replace(\"-\", \"_\")\n    return sanitized\n\n\ndef parse_intent_summary(code: str, language: str) -> Dict[str, Any]:\n    \"\"\"Extract semantic intent from source code.\"\"\"\n    summary: Dict[str, Any] = {\n        \"language\": language,\n        \"length\": len(code or \"\"),\n        \"lines\": len((code or \"\").splitlines()),\n        \"keywords\": [],\n    }\n\n    keywords = [\n        # control flow\n        \"if\", \"else\", \"elif\", \"switch\", \"case\", \"default\",\n        \"for\", \"while\", \"do\", \"foreach\", \"loop\", \"until\", \"break\", \"continue\",\n        # functions\n        \"def\", \"function\", \"fn\", \"func\", \"procedure\", \"subroutine\", \"method\",\n        # classes\n        \"class\", \"struct\", \"interface\", \"trait\", \"protocol\", \"object\",\n        # variables\n        \"let\", \"const\", \"var\", \"val\", \"mut\",\n        # io\n        \"print\", \"console.log\", \"printf\", \"puts\", \"echo\", \"write\", \"read\",\n        # imports\n        \"import\", \"from\", \"include\", \"require\", \"export\", \"module\",\n        # operators\n        \"return\", \"yield\", \"throw\", \"try\", \"catch\", \"finally\",\n        # visibility\n        \"public\", \"private\", \"protected\", \"static\", \"final\",\n        # database\n        \"select\", \"insert\", \"update\", \"delete\", \"create\", \"drop\",\n        # type\n        \"type\", \"typeof\", \"cast\", \"as\", \"is\",\n    ]\n\n    code_lower = (code or \"\").lower()\n    for item in keywords:\n        if item in code_lower:\n            summary[\"keywords\"].append(item)\n\n    return summary\n